rawVcf: "/exports/cmvm/eddie/eb/groups/HighlanderLab/jobsteter/Honeybees/GenomicData/Amel_HapMap/test.vcf.gz"
alignedFocal: "/exports/cmvm/eddie/eb/groups/HighlanderLab/jobsteter/Honeybees/MultipleGenomeAlignment/Focal_aligned/alignedTest.txt"
noEstSfsChunks: 1000
estsfsConfig: "config-kimura_3o.txt"
